# Python Basics:

## Control statements:

In [ ]:
#Control Statements: if and else
a = 9
if a>10:
    print(f"{a} is greater than 10")
else:
    print(f"{a} is lesser than 10")

9 is lesser than 10


In [71]:
#Control Statements: if, elif and else
a = 10
if a>10:
    print(f"{a} is greater than 10")
elif a==0:
    print("The number is zero")
else:
    print(f"{a} is less than to 10")

10 is less than to 10


In [72]:
range(10)

range(0, 10)

In [74]:
#Looping: for
for i in range(2,10,2):
    print(i)

2
4
6
8


In [84]:
a=[1,2,3]
b=a
print(b)
a.append(4)
print(b)

[1, 2, 3]
[1, 2, 3, 4]


In [75]:
#Looping: for
for i in ["a","b","c"]:
    print(i)

a
b
c


In [5]:
#Looping: while
i = 10
while i>9:
    print(i)

10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
1

KeyboardInterrupt: 

In [ ]:
#Control Statement: break
i=20
while i>9:
    print(i)
    i=i-1

10


In [8]:
#Control Statement: continue
for i in range(10):
    if i>5:
        continue
    print(i)

0
1
2
3
4
5


In [9]:
#Control Statement: pass
for i in range(10):
    if i>5:
        pass
    print(i)

0
1
2
3
4
5
6
7
8
9


## Functions:

In [ ]:
#Function definition
#Calculator
def add(a,b):
    return a + b
def sub(a,b):

def mult(a,b):

def div(a,b):

#add("hello","tthere")
#Error
# try except, TypeError
# Invalid input
# Please enter numbers - int / float
# 'a' is a string. Plese enter int/float
# b is int, a is a string. please enter a as integer.
#
# do u want to allow these inputs at all?
# if u allow these inputs then what output do u want to show?

TypeError: can only concatenate str (not "int") to str

In [11]:
#Built in functions: range, len, abs, max, min ... and many more
test = [-1,-2,3,4,8,90]
len(test)

6

In [12]:
#Importing modules
import numpy as np
import scipy
import pandas as pd

## Object Oriented Programming:

In [ ]:
a=10
b='Good morning'

In [13]:
#Class and attributes
class Car:
    model = "maruthi"
    number = 2033

In [14]:
car = Car()

In [15]:
car.model = 'toyota'
car.model

'toyota'

In [87]:
#Method
class Car:
    def __init__(self, model, number):
        self.model = model
        self.number = number
    def mod_num(self):
        print(f"The car model is {self.model} and number is {self.number}")

In [88]:
#Method examples
car = Car("toyota",1234)
car.model

'toyota'

In [18]:
car.mod_num()

The car model is toyota and number is 1234


In [89]:
#Inheritance
class Car:
    def __init__(self, model, number):
        self.model = model
        self.number = number
    def mod_num(self,model):
        return model

class Engine(Car):
    def __init__(self, model, engine):
        self.engine = engine
        self.model = model
    def mod_engine(self):
        print(f"The car model is {self.mod_num(self.model)} and number is {self.engine}")

In [20]:
Engine('toyota','v6').mod_engine()

The car model is toyota and number is v6


In [ ]:
#Encapsulation
class Car:
    def __init__(self):
        self.__model = 'toyota'
    def sell(self):
        print(f"I am selling my {self.__model} car")
        
car = Car()
car.__model = 1000
car.sell()


I am selling my toyota car


In [22]:
#Polymorphism
class Car:
    def __init__(self):
        self.model = 'toyota'
    def sell(self):
        print(f"I am selling my {self.model} car")
class Maruthi(Car):
    def __init__(self):
        self.model = 'maruthi'
    def sell(self):
        print(f"I am selling my {self.model} car")
        
Maruthi().sell()

I am selling my maruthi car


# NumPy:

In [91]:
test = [i for i in range(10000)]

# Speed of numpy vs python

In [47]:
# Data setup
N = 1_000_000
a = np.random.randn(N)   # NumPy array
la = a.tolist()          # Python list version (same values)

# Functions to benchmark
def py_filter():
    return [x for x in la if x > 0]

def np_filter():
    return a[a > 0]

print("1) Python list (list comprehension over la):")
%timeit py_filter()

print("\n2) NumPy array (boolean mask over a):")
%timeit np_filter()

1) Python list (list comprehension over la):
32.4 ms ± 1.31 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

2) NumPy array (boolean mask over a):
5.74 ms ± 194 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [48]:
import numpy as np

# Synthetic regression data
n_samples = 200_000
n_features = 50

X = np.random.randn(n_samples, n_features)
y = np.random.randn(n_samples)

w = np.random.randn(n_features)
b = 0.1
lr = 1e-3

# Python-list versions of the same data
XL = X.tolist()
yL = y.tolist()
wL = w.tolist()


def predict_python():
    # Returns list of predictions
    out = []
    for i in range(n_samples):
        s = b
        row = XL[i]
        for j in range(n_features):
            s += row[j] * wL[j]
        out.append(s)
    return out

def predict_numpy():
    return X @ w + b


print("1) Python loops: linear regression prediction (list of lists):")
%timeit predict_python()

print("\n2) NumPy vectorized: linear regression prediction (X @ w + b):")
%timeit predict_numpy()


1) Python loops: linear regression prediction (list of lists):
682 ms ± 30.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

2) NumPy vectorized: linear regression prediction (X @ w + b):
7.13 ms ± 352 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [93]:
#Array creation
ar1 = np.arange(25)
ar1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
np.linspace(20, 145, 5)

array([ 20.  ,  51.25,  82.5 , 113.75, 145.  ])

In [51]:
ar1.shape

(20,)

In [52]:
ar1.size

20

In [53]:
ar1.ndim

1

In [94]:
ar1.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [96]:
np.linalg.inv(ar1.reshape(5,5))

LinAlgError: Singular matrix

In [55]:
ar1**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361])

In [56]:
ar1 + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21])

In [57]:
#Elementwise operations
ar1 - ar1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [58]:
ar1 - np.random.rand(20)

array([-0.80075435,  0.3468297 ,  1.31613912,  2.83281169,  3.98970983,
        4.00758834,  5.79696994,  6.22181752,  7.66477651,  8.01704121,
        9.48700084, 10.85638331, 11.7782486 , 12.26477295, 13.3946016 ,
       14.6666747 , 15.28531757, 16.72898004, 17.53469164, 18.2377716 ])

In [59]:
#Indexing and slicing
ar1[0]

0

In [ ]:
# Can i write a random number generator - some language - C, python, matlab,java
# UniForm distribution [0,10]
# epoch time 01/01/1970 in milliseconds
# 1.1 , 3.4, 6.7, 4, 2,6 ,9.8
# 1000 samples 
# 0 ,1 
# 0 = 600
# 1 = 400
# train test split.
# 1000 samples
# 70% of my data - train - 700
# 30% as test  - 300 
# seed (1000) - if u want repeatability
# else seed is random

In [60]:
ar1[:3]

array([0, 1, 2])

In [61]:
ar1[[1,4,5]]

array([1, 4, 5])

In [62]:
#Boolean arrays
ar1>5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [ ]:
#Element wise  multiplication
ar1*ar1

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361])

In [ ]:
#Matrix Multiplication
ar1@ar1

2470

In [66]:
#Linear algebra functions: inv, norm, dot, vdot, svd, eig, eigh and many more
np.linalg.inv(np.random.randn(4,4))

array([[-0.04023711, -0.66520696,  1.07492263, -0.87530955],
       [-2.13424562,  3.50680238, -5.31730676,  7.1151937 ],
       [-0.37295894,  1.12650898, -1.94042491,  2.6778419 ],
       [ 1.45755595, -1.7315856 ,  1.0816229 , -3.23431922]])

# pandas

In [ ]:
#Load data functions: read_csv, read_excel
import seaborn as sns
iris = sns.load_dataset('iris')
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
iris.tail()

sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [ ]:
#Indexing
iris['sepal_length']

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

In [ ]:
iris['sepal_length'][0]

5.1

In [ ]:
iris.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [ ]:
iris.index

RangeIndex(start=0, stop=150, step=1)

In [ ]:
iris.iloc[1,1]

3.0

In [ ]:
#Statistics: mean, std, median, mode
iris['sepal_length'].mean()

5.843333333333334

In [ ]:
#Summary
iris.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [ ]:
#Dropping
iris.dropna()

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [ ]:
iris.dropna(inplace=True)

In [ ]:
iris.drop_duplicates()

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[149 rows x 5 columns]

In [ ]:
#Grouping
iris.groupby("species").mean()

sepal_length  sepal_width  petal_length  petal_width
species                                                         
setosa             5.006        3.428         1.462        0.246
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026

In [ ]:
iris['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [ ]:
iris['new'] = iris['sepal_length'] + 2

In [ ]:
iris.head()

sepal_length  sepal_width  petal_length  petal_width species  new
0           5.1          3.5           1.4          0.2  setosa  7.1
1           4.9          3.0           1.4          0.2  setosa  6.9
2           4.7          3.2           1.3          0.2  setosa  6.7
3           4.6          3.1           1.5          0.2  setosa  6.6
4           5.0          3.6           1.4          0.2  setosa  7.0

In [ ]:
iris.drop('new',axis=1)

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [ ]:
iris.sort_values(by=['sepal_length'],ascending=True)

sepal_length  sepal_width  petal_length  petal_width    species  new
13            4.3          3.0           1.1          0.1     setosa  6.3
42            4.4          3.2           1.3          0.2     setosa  6.4
38            4.4          3.0           1.3          0.2     setosa  6.4
8             4.4          2.9           1.4          0.2     setosa  6.4
41            4.5          2.3           1.3          0.3     setosa  6.5
..            ...          ...           ...          ...        ...  ...
122           7.7          2.8           6.7          2.0  virginica  9.7
118           7.7          2.6           6.9          2.3  virginica  9.7
117           7.7          3.8           6.7          2.2  virginica  9.7
135           7.7          3.0           6.1          2.3  virginica  9.7
131           7.9          3.8           6.4          2.0  virginica  9.9

[150 rows x 6 columns]

# Scipy

In [ ]:
from scipy import constants, special, integrate, optimize, interpolate, fftpack, signal, linalg, stats
import numpy as np

# 1. Constants & Special Functions
print(f"Pi: {constants.pi}, Speed of Light: {constants.c}")
print(f"Bessel Function (j0): {special.jn(0, 1.0)}")

# 2. Integration (integrate)
val, err = integrate.quad(lambda x: x**2, 0, 1)
print(f"Integral of x^2 [0,1]: {val:.4f}")

# 3. Linear Algebra (linalg)
A = np.array([[1, 2], [3, 4]])
print("Determinant:", linalg.det(A))
print("Inverse:\n", linalg.inv(A))

# 4. Fourier Transforms (fftpack)
sig = np.array([1, 2, 1, -1, 1.5])
print("FFT:", fftpack.fft(sig))

# 5. Signal Processing (signal)
print("Resampled Signal:", signal.resample(sig, 10))

### Interpolation & Statistics
- `interpolate`: Smoothing data.
- `stats`: Statistical distributions.

In [ ]:
# Interpolation
x = np.arange(10)
y = np.sin(x)
f = interpolate.interp1d(x, y, kind='cubic')
print("Interpolated value at 4.5:", f(4.5))

# Statistics
print("Normal PDF at 0:", stats.norm.pdf(0))
print("Random Normal Samples:", stats.norm.rvs(size=5))

In [ ]:
from scipy.optimize import minimize, curve_fit
import matplotlib.pyplot as plt

# --- 1. Optimization Example ---
# Objective: Minimize f(x) = x^2 + 10*sin(x)
def f(x):
    return x**2 + 10*np.sin(x)

res = minimize(f, x0=0)
print(f"Global Minimum found at x = {res.x[0]:.4f}")

# --- 2. Regression Example (Curve Fitting) ---
# Data: y = a * exp(b * x) + noise
def model(x, a, b):
    return a * np.exp(b * x)

x_data = np.linspace(0, 2, 50)
y_data = model(x_data, 2.5, 1.3) + 0.5 * np.random.normal(size=50)

popt, _ = curve_fit(model, x_data, y_data)
print(f"Regression Parameters: a={popt[0]:.2f}, b={popt[1]:.2f}")

# Visualization
plt.scatter(x_data, y_data, label='Data')
plt.plot(x_data, model(x_data, *popt), 'r', label='Fitted Curve')
plt.legend()
plt.title("Non-linear Regression with SciPy")
plt.show()